# Generated by Django 3.2.7 on 2022-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_squashed_0002_auto_20220120_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='common2_analysis',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='obfuscation_name',
            field=models.CharField(choices=[('unknown', 'Unknown / Any / Not specified'), ('andstr', 'AndStrObfuscator - https://github.com/cyoyochoo/AndStrObfuscator'), ('andresguard', 'AndResGuard - https://github.com/shwenzhang/AndResGuard'), ('dasho', 'DashO - https://www.preemptive.com/products/dasho'), ('dexprotector', 'https://dexprotector.com'), ('enigma', 'Enigma - https://github.com/christopherney/Enigma'), ('javaguard', 'JavaGuard - https://sourceforge.net/projects/javaguard/ '), ('paranoid', 'Paranoid - https://github.com/MichaelRocks/paranoid'), ('proguard', 'Proguard'), ('zelix', 'Zelix KlassMaster - http://www.zelix.com/klassmaster/')], default='unknown', max_length=200, null=True),
        ),
    ]
