# Generated by Django 3.2.7 on 2022-01-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_squashed_0006_auto_20211005_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malware',
            options={'ordering': ['-id'], 'verbose_name_plural': 'malware'},
        ),
        migrations.AddField(
            model_name='property',
            name='call_ussd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='privacy2_remotecontrol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='packer_name',
            field=models.CharField(choices=[('unknown', 'Unknown / Any / Not specified'), ('apkencryptor', 'ApkEncryptor - https://github.com/FlyingYu-Z/ApkEncryptor'), ('apkguard', 'APKGuard - http://apkguard.io'), ('apkprotect', 'ApkProtect'), ('appsealing', 'AppSealing Loader - https://www.appsealing.com'), ('bangle', 'Bangcle'), ('baidu', 'Baidu'), ('cryptoshell', 'CryptoShell - http://cryptoshell.io'), ('divilar', 'Divilar'), ('gaoxor', 'GaoXor'), ('ijiami', 'Ijiami'), ('medusah', 'Medusah'), ('multidex', 'Multidex'), ('kiwisec', 'Kiwisec'), ('pangxie', 'PangXie'), ('qihoo', 'Qihoo'), ('legu', 'Tencent  Legu'), ('tencent', 'Mobile Tencent Protect - https://intl.cloud.tencent.com/product/mtp')], default='unknown', max_length=200, null=True),
        ),
    ]
