"""
Django settings for androscope project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = False

if DEBUG:
    print("DEBUG MODE: Do not forget to use DJANGO_SECRET_KEY for deploy environment")
    SECRET_KEY = 'SET_THIS_KEY_YOURSELF_DONT_USE_FOR_DEPLOY'
else:
    print("PRODUCTION MODE")
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
    ALLOWED_HOSTS = ['127.0.0.1',os.environ['DJANGO_WEBSITE_FQDN']]
    SECURE_SSL_REDIRECT = False
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
# Application definition

INSTALLED_APPS = [
    'add.apps.AddConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'androscope.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'androscope/templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries' : {
                'is_in_group' : 'androscope.templatetags.is_in_group'
                }
        },
    },
]

LOGIN_REDIRECT_URL = '/add/'
LOGOUT_REDIRECT_URL = '/'

WSGI_APPLICATION = 'androscope.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'
if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    print("DEBUG MODE: static dirs={}".format(STATICFILES_DIRS))
else:
    STATIC_ROOT = './static'


# BigInt for Django 3.2
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Captcha - https://django-simple-captcha.readthedocs.io
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_LETTER_ROTATION = (-20, 20)
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)

# VIRUSTOTAL API KEY
if 'VIRUSTOTAL_APIKEY' in os.environ:
    VIRUSTOTAL_APIKEY = os.environ['VIRUSTOTAL_APIKEY']
else:
    VIRUSTOTAL_APIKEY = ''

# KOODOUS API KEY
if 'KOODOUS_APIKEY' in os.environ:
    KOODOUS_APIKEY = os.environ['KOODOUS_APIKEY']
else:
    KOODOUS_APIKEY = ''


